name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  PLUGIN_NAME: format-hotkeys-obsidian
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Load yarn cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Build plugin
        run: yarn build

      - name: Package plugin
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp dist/* ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            manifest.json
            dist/main.js
            dist/styles.css
            ${{ env.PLUGIN_NAME }}.zip

      - name: Commit manifest
        uses: EndBug/add-and-commit@v7
        with:
          add: "manifest.json"
          message: "[GitHub Actions] Automatic manifest update"
