name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  PLUGIN_NAME: format-hotkeys-obsidian
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Load npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-    - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build plugin
        run: npm run build

      - name: Package plugin
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp dist/* ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/main.js
            dist/styles.css
            dist/manifest.json
            ${{ env.PLUGIN_NAME }}.zip